source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BigBoard_Example', :exclusive => true do
  pod 'BigBoard', :path => '../'
  pod 'AlamofireObjectMapper', '~> 3.0'
end

target 'BigBoard_Tests', :exclusive => true do
  pod 'BigBoard', :path => '../'

  
end
